let state=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const money=v=>{const n=Number(v||0);return new Intl.NumberFormat("en-ZA",{style:"currency",currency:"ZAR",maximumFractionDigits:0}).format(n)};
const badge=v=>{const x=String(v??"unknown"),l=x.toLowerCase(),cls=/paid|approved|ready|complete|sent|valid|live|released|qualified|passed/.test(l)?"good":/fail|blocked|rejected|invalid|error|restricted/.test(l)?"bad":/pending|hold|draft|review|unknown|await|unsettled/.test(l)?"warn":"muted";return `<span class="badge ${cls}">${esc(x.replaceAll("_"," "))}</span>`};
const pathHref=p=>p?`/${String(p).replace(/^\/+/,"")}`:"#";
function toast(msg,bad=false){const t=$("#toast");t.textContent=msg;t.className=`toast show${bad?" bad":""}`;clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.className="toast",4200)}
async function api(path,payload){const r=await fetch(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.message||body.error||`HTTP ${r.status}`);return body}
async function fetchJSON(path){try{const r=await fetch(path,{cache:'no-store'});if(!r.ok)return null;return await r.json()}catch{return null}}
function relTime(iso){if(!iso)return '-';const t=new Date(iso).getTime();if(!Number.isFinite(t))return '-';const mins=Math.max(0,Math.round((Date.now()-t)/60000));if(mins<60)return `${mins}m`;const hrs=Math.round(mins/60);if(hrs<48)return `${hrs}h`;return `${Math.round(hrs/24)}d`}
function humanCampaignId(raw){const a=raw?.attribution||{};return a.campaign_id||a.utm_campaign||''}
function hypForCampaign(id){return (supplemental.hypotheses||[]).find(h=>String(h.campaign_id||'').toLowerCase()===String(id||'').toLowerCase())}
function waveCampaign(id){return (state.market_campaigns||[]).find(c=>String(c.campaign_id||'').toLowerCase()===String(id||'').toLowerCase())}
function marketContent(id){return (state.market_command?.content_items||[]).filter(c=>String(c.campaign_id||'')===String(id||''))}
async function runAction(path,payload,label){if(!confirm(label))return;try{toast("Executing governed action...");await api(path,{...payload,confirmed:true});toast("Action completed. Refreshing tactical picture.");await loadState()}catch(e){toast(e.message,true)}}
function switchView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));window.scrollTo({top:0,behavior:'smooth'})}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));

function actionForAttention(a){
  const id=a.entity_id;
  const product=(state.product_workflows||[]).find(x=>x.job_id===id);if(product&&product.action)return `<button class="mini gold" onclick="productAction('${esc(id)}','${esc(product.action)}')">${esc(product.action.replaceAll('-',' '))}</button>`;
  const sophia=(state.sophia_jobs||[]).find(x=>x.job_id===id);if(sophia&&sophia.action)return `<button class="mini gold" onclick="specialAction('sophia','${esc(id)}','${esc(sophia.action)}')">${esc(sophia.action.replaceAll('-',' '))}</button>`;
  const vamp=(state.vamp_jobs||[]).find(x=>x.job_id===id);if(vamp&&vamp.action)return `<button class="mini gold" onclick="specialAction('vamp','${esc(id)}','${esc(vamp.action)}')">${esc(vamp.action.replaceAll('-',' '))}</button>`;
  const mail=(state.mail_intents||[]).find(x=>x.mail_intent_id===id);if(mail&&!['sent','rejected'].includes(mail.send_state)){const act=mail.provider_draft_ready?'approve-send':'outlook-draft';return `<button class="mini gold" onclick="mailAction('${esc(id)}','${act}')">${act==='approve-send'?'approve & send':'create draft'}</button>`}
  const lead=(state.leads||[]).find(x=>x.lead_id===id);if(lead&&lead.qualification==='pending')return `<button class="mini gold" onclick="leadAction('${esc(id)}','qualify')">qualify</button>`;
  const vid=(state.video_candidates||[]).find(x=>x.episode_id===id);if(vid){const reviewed=vid.watch_approved&&vid.voice_approved&&vid.thumbnail_approved&&vid.metadata_approved,uploaded=Boolean(vid.youtube&&vid.youtube.video_id),pub=vid.youtube&&vid.youtube.privacy_status==='public';const act=pub?'':uploaded?'publish-public':reviewed?'upload-private':'approve-review';if(act)return `<button class="mini gold" onclick="videoAction('${esc(id)}','${act}')">${esc(act.replaceAll('-',' '))}</button>`}
  return a.link?`<a class="mini" href="${pathHref(a.link)}">inspect</a>`:`<a class="mini" href="/dashboard/index.html">open deck</a>`;
}
window.productAction=(id,action)=>runAction('/api/control/product/action',{job_id:id,action},`Confirm ${action.replaceAll('-',' ')} for ${id}?`);
window.specialAction=(kind,id,action)=>runAction(`/api/control/${kind}/action`,{job_id:id,action},`Confirm ${kind.toUpperCase()} ${action.replaceAll('-',' ')} for ${id}?`);
window.leadAction=(id,action)=>runAction('/api/control/lead/action',{lead_id:id,action},`Confirm ${action} lead ${id}?`);
window.mailAction=(id,action)=>runAction('/api/control/mail/action',{mail_intent_id:id,action,recipient_confirmed:true},action==='approve-send'?`SEND the reviewed Outlook draft for ${id}?`:`Create the exact Outlook draft for ${id}?`);
window.videoAction=(id,action)=>runAction('/api/control/video/action',{episode_id:id,action},`Confirm video ${action.replaceAll('-',' ')} for ${id}?`);

function buildCustomers(){const rows=[];
  for(const l of state.leads||[])if(!['closed','rejected'].includes(l.qualification))rows.push({name:l.name||l.email||l.lead_id,sub:`${String(l.product||'').toUpperCase()} · ${l.offer||'intake'} · ${l.qualification}`,value:'LEAD'});
  for(const j of state.product_workflows||[])if(!['closed','delivered'].includes(j.state))rows.push({name:j.recipient||j.job_id,sub:`${String(j.product||'').toUpperCase()} · ${j.processing_state} · ${j.notification_state}`,value:'ACTIVE'});
  for(const j of [...(state.sophia_jobs||[]),...(state.vamp_jobs||[])])if(!['closed','delivered'].includes(j.state))rows.push({name:j.recipient||j.customer_email||j.job_id,sub:`${String(j.job_id).split('-')[0]} · ${j.state} · ${j.delivery_state||'pending'}`,value:'ACTIVE'});
  return rows.slice(0,7)}
function buildReady(){const rows=[];for(const j of state.product_workflows||[])if(j.output_dir&&['approved','review_ready','outlook_ready'].includes(j.output_review_state)||j.notification_state==='outlook_ready')rows.push({name:`${String(j.product||'').toUpperCase()} · ${j.job_id}`,sub:`output ${j.output_review_state} · notification ${j.notification_state}`,value:'PACK'});for(const j of [...(state.sophia_jobs||[]),...(state.vamp_jobs||[])])if(j.output_dir&&['approved','outlook_ready','ready'].includes(j.approval_state)||j.outlook_draft_ready)rows.push({name:j.job_id,sub:`approval ${j.approval_state} · delivery ${j.delivery_state}`,value:'PACK'});for(const v of state.video_candidates||[])if(v.preflight_passed)rows.push({name:v.title,sub:`${v.product_id} · ${v.status}`,value:'FILM'});return rows.slice(0,7)}
function renderList(target,rows){$(target).innerHTML=rows.length?rows.map(r=>`<div class="list-row"><div><b>${esc(r.name)}</b><span>${esc(r.sub)}</span></div><div class="value">${esc(r.value)}</div></div>`).join(''):'<div class="empty">Nothing waiting here.</div>'}

function render(){const m=state.metrics||{};$("#eyeNeeds").textContent=m.needs_you||0;$("#needsCount").textContent=`${m.needs_you||0} action${m.needs_you===1?'':'s'}`;$("#orbitRevenue").textContent=`Revenue · ${money(m.revenue)}`;$("#orbitJobs").textContent=`Jobs · ${m.active_jobs||0}`;$("#orbitLeads").textContent=`Leads · ${m.leads||0}`;$("#orbitRisk").textContent=`Risk · ${m.failures||0} fail`;
  $("#eyeTime").textContent=new Date(state.generated_at).toLocaleString();$("#sideGenerated").textContent=`State ${new Date(state.generated_at).toLocaleTimeString()}`;$("#headerState").textContent=(m.failures||0)?`${m.failures} failures · ${m.needs_you||0} decisions waiting`:`${m.needs_you||0} decisions waiting · systems nominal`;
  const k=[['Qualified leads',m.leads||0,'current commercial interest'],['Paid orders',m.orders||0,'provider-backed'],['Revenue',money(m.revenue),'recorded telemetry'],['Active jobs',m.active_jobs||0,'not closed or delivered'],['Needs you',m.needs_you||0,'human gate reached'],['Failures',m.failures||0,'technical failures']];$("#kpis").innerHTML=k.map(([a,b,c])=>`<div class="kpi"><span>${a}</span><strong>${b}</strong><small>${c}</small></div>`).join('');$("#commerceKpis").innerHTML=k.map(([a,b,c])=>`<div class="kpi"><span>${a}</span><strong>${b}</strong><small>${c}</small></div>`).join('');
  const att=(state.attention||[]).filter(a=>['critical','action'].includes(a.severity));$("#needsList").innerHTML=att.length?att.slice(0,10).map(a=>`<div class="mission"><i class="dot ${esc(a.severity)}"></i><div class="mission-copy"><b>${esc(a.title)}</b><span>${esc(a.detail)}</span><small>${esc(a.kind)} · ${esc(a.entity_id)}</small></div><div class="mission-action">${actionForAttention(a)}</div></div>`).join(''):'<div class="empty">No operator decision is currently required. The eye is quiet.</div>';
  renderList('#customersList',buildCustomers());renderList('#shipList',buildReady());renderList('#activityList',(state.activity||[]).slice(0,7).map(x=>({name:x.event,sub:`${x.entity_type} · ${x.entity_id}`,value:x.occurred_at?new Date(x.occurred_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'EVENT'})));
  renderMissions();renderCommerce();renderMarket();renderHypotheses();renderRegistry();renderLineage();renderExceptions();renderPolicy();renderSystems();lucide.createIcons();
}
function renderMissions(){const rows=[];for(const j of state.product_workflows||[])if(!['closed','delivered'].includes(j.state))rows.push({product:j.product,id:j.job_id,human:j.recipient||'controlled',state:`${j.processing_state} / ${j.notification_state}`,money:'-',why:j.notification_state==='outlook_ready'?'Awaiting review of exact Outlook draft':j.action?`DIO stopped for: ${j.action.replaceAll('-',' ')}`:'Active',action:j.action?`<button class="mini gold" onclick="productAction('${esc(j.job_id)}','${esc(j.action)}')">${esc(j.action.replaceAll('-',' '))}</button>`:`<a class="mini" href="${pathHref(j.path)}">inspect</a>`});for(const j of state.sophia_jobs||[])if(!['closed','delivered'].includes(j.state))rows.push({product:'sophia',id:j.job_id,human:j.recipient||j.customer_email||'customer',state:`${j.review_state||j.state} / ${j.delivery_state||'pending'}`,money:j.amount_minor?money(Number(j.amount_minor)/100):'$',why:j.action?`DIO stopped for: ${j.action.replaceAll('-',' ')}`:'Active',action:j.action?`<button class="mini gold" onclick="specialAction('sophia','${esc(j.job_id)}','${esc(j.action)}')">${esc(j.action.replaceAll('-',' '))}</button>`:'-'});for(const j of state.vamp_jobs||[])if(!['closed','delivered'].includes(j.state))rows.push({product:'vamp',id:j.job_id,human:j.recipient||j.customer_email||'customer',state:`${j.snapshot_state||j.state} / ${j.delivery_state||'pending'}`,money:j.amount_minor?money(Number(j.amount_minor)/100):'$',why:j.action?`DIO stopped for: ${j.action.replaceAll('-',' ')}`:'Active',action:j.action?`<button class="mini gold" onclick="specialAction('vamp','${esc(j.job_id)}','${esc(j.action)}')">${esc(j.action.replaceAll('-',' '))}</button>`:'-'});$("#missionRows").innerHTML=rows.length?rows.map(r=>`<tr><td><b>${esc(String(r.product).toUpperCase())}</b></td><td><code>${esc(r.id)}</code></td><td>${esc(r.human)}</td><td>${badge(r.state)}</td><td>${esc(r.money)}</td><td>${esc(r.why)}</td><td>${r.action}</td></tr>`).join(''):'<tr><td colspan="7">No active missions.</td></tr>'}
function renderCommerce(){
  const raw=supplemental.rawLeads||{};
  $("#leadRows").innerHTML=(state.leads||[]).map(l=>{const r=raw[l.lead_id]||{},a=r.attribution||{},cid=a.campaign_id||'';return `<tr><td><b>${esc(l.name||l.email||l.lead_id)}</b><br><small>${esc(l.email||'')}</small></td><td>${esc(String(l.product||'').toUpperCase())}</td><td>${esc(a.source||'-')}<br><small>${esc(a.medium||'')}</small></td><td>${cid?`<code>${esc(cid)}</code>`:badge('unattributed')}</td><td>${esc(l.offer||'')}</td><td>${esc(relTime(l.created_at))}</td><td>${badge(l.qualification)}</td><td>${l.qualification==='pending'?`<button class="mini gold" onclick="leadAction('${esc(l.lead_id)}','qualify')">qualify</button> <button class="mini red" onclick="leadAction('${esc(l.lead_id)}','reject')">reject</button>`:'-'}</td></tr>`}).join('')||'<tr><td colspan="8">No leads.</td></tr>';
  $("#transactionRows").innerHTML=(state.transactions||[]).map(t=>`<tr><td><b>${esc(String(t.product||'').toUpperCase())}</b><br><small>${esc(t.transaction_id||'')}</small></td><td>${badge(t.stage)}</td><td>${badge(t.payment_state||'not started')}</td><td>${badge(t.verdict)}<br><small>Loki ${esc(t.loki_status||'')} · discord ${Math.round(Number(t.discord_score||0)*100)}%</small></td></tr>`).join('')||'<tr><td colspan="4">No canonical transactions.</td></tr>';
  $("#orderRows").innerHTML=(state.orders||[]).map(o=>`<tr><td><code>${esc(o.order_id)}</code></td><td>${esc(o.product_code)}</td><td>${esc(o.currency||'')} ${esc(((o.amount_minor||0)/100).toFixed(2))}</td><td>${badge(o.payment_state)}</td></tr>`).join('')||'<tr><td colspan="4">No orders.</td></tr>'
}
