function renderPolicy(){const labels={outbound_mail:'Outbound mail',automation:'Automation',fulfilment_release:'Fulfilment release',lead_capture:'Lead capture',data_processing:'Data processing',campaign_release:'Campaign release',invoice_authority:'Invoice authority',payment_mode:'Payment mode'},next={outbound_mail:{off:'on',on:'off'},automation:{paused:'running',running:'paused'},fulfilment_release:{hold:'release',release:'hold'},lead_capture:{hold:'accept',accept:'hold'},data_processing:{hold:'process',process:'hold'},campaign_release:{hold:'release',release:'hold'},invoice_authority:{draft_only:'issue',issue:'draft_only'},payment_mode:{sandbox:'live',live:'sandbox'}};$("#policyGrid").innerHTML=Object.entries(labels).map(([k,label])=>{const v=state.control_policy?.[k]||'unknown',on=['on','running','release','accept','process','issue','live'].includes(v);return `<div class="policy"><div class="policy-copy"><b>${label}</b><span>${on?'authority available':'held or constrained'}</span></div><button class="switch ${on?'on':'danger'}" onclick="togglePolicy('${k}','${esc(next[k]?.[v]||v)}')">${esc(v.replaceAll('_',' '))}</button></div>`}).join('')}
window.togglePolicy=async(k,v)=>{const loud=['live','release','issue','on','running'].includes(v);if(!confirm(`${loud?'ENABLE':'Set'} ${k.replaceAll('_',' ')} = ${v}?`))return;try{await api('/api/control/policy',{[k]:v});toast('Control matrix updated.');await loadState()}catch(e){toast(e.message,true)}};
function renderSystems(){$("#systemRows").innerHTML=(state.systems||[]).map(s=>`<tr><td><b>${esc(s.name)}</b></td><td>${badge(s.state)}</td><td>${esc(s.detail||'')}</td></tr>`).join('')||'<tr><td colspan="3">No system inventory.</td></tr>'}

async function loadMandos(){let journal=[],neg=null;try{const r=await fetch('/state/mandos/JOURNAL.jsonl',{cache:'no-store'});if(r.ok){const text=await r.text();journal=text.split(/\n+/).filter(Boolean).map(line=>{try{return JSON.parse(line)}catch{return null}}).filter(Boolean)}}catch{}try{const r=await fetch('/state/mandos/beast/NEGATIVE_CAPABILITIES.json',{cache:'no-store'});if(r.ok)neg=await r.json()}catch{}const stringify=JSON.stringify(neg||{}).toLowerCase(),active=(stringify.match(/"active"/g)||[]).length,contested=(stringify.match(/"contested"/g)||[]).length;$("#mandosJournal").textContent=journal.length;$("#mandosActive").textContent=active;$("#mandosContested").textContent=contested;$("#mandosState").textContent=journal.length||neg?'memory online':'no runtime memory exported';$("#mandosRecent").innerHTML=journal.length?journal.slice(-8).reverse().map(x=>`<div class="list-row"><div><b>${esc(x.outcome_id||x.entry_id||x.event||'Mandos journal entry')}</b><span>${esc(x.outcome_type||x.polarity||x.case_id||'tamper-evident attestation')}</span></div><div>${badge(x.polarity||x.state||'recorded')}</div></div>`).join(''):'<div class="empty">Mandos code is present, but no runtime journal is currently exported under state/mandos on this checkout.</div>';let negRows=[];const walk=x=>{if(Array.isArray(x))x.forEach(walk);else if(x&&typeof x==='object'){if(x.state==='active'||x.status==='active'||x.stage==='active')negRows.push(x);Object.values(x).forEach(walk)}};walk(neg);$("#negativeList").innerHTML=negRows.length?negRows.slice(0,10).map(x=>`<div class="list-row"><div><b>${esc(x.pattern_key||x.tactic_id||x.product||x.id||'remembered failure')}</b><span>${esc(x.reason||x.summary||x.state||'active negative capability')}</span></div><div>${badge('active')}</div></div>`).join(''):'<div class="empty">No active negative capabilities surfaced by the runtime registry.</div>'}
async function loadCommercialSupplemental(){
  supplemental={registry:null,registryFull:null,hypotheses:[],rawLeads:{},measurements:{},settlements:{}};
  supplemental.registry=await fetchJSON('/campaigns/dio_market_loop/wave4/REGISTRY_IMPORT_RECEIPT.json');
  supplemental.registryFull=await fetchJSON('/api/goldeneye/registry');
  const records=supplemental.registry?.hivenance_register_sync?.records||[];
  supplemental.hypotheses=(await Promise.all(records.map(r=>fetchJSON(`/campaigns/dio_market_loop/wave4/hivenance_registry/${encodeURIComponent(r.hypothesis_id)}.json`)))).filter(Boolean);
  await Promise.all((state.leads||[]).map(async l=>{const raw=await fetchJSON(pathHref(l.path));if(raw)supplemental.rawLeads[l.lead_id]=raw}));
  await Promise.all((state.market_campaigns||[]).map(async c=>{if(c.measurement){const m=await fetchJSON(pathHref(c.measurement));if(m)supplemental.measurements[c.campaign_id]=m}if(c.pack){const p=String(c.pack).replace(/CAMPAIGN_PACK\.md$/,'HIVENANCE_SETTLEMENT.json');const st=await fetchJSON(pathHref(p));if(st)supplemental.settlements[c.campaign_id]=st}}));
}
async function loadState(){try{const r=await fetch('/api/control/state',{cache:'no-store'});if(!r.ok)throw new Error(`state_http_${r.status}`);state=await r.json();await loadCommercialSupplemental();render();await loadMandos()}catch(e){toast(`GoldenEye could not load state: ${e.message}`,true)}}
async function blackout(){if(!confirm('BLACKOUT pauses automation and holds outbound mail, data processing, fulfilment, campaign release and invoice authority. Continue?'))return;try{await api('/api/control/policy',{outbound_mail:'off',automation:'paused',fulfilment_release:'hold',data_processing:'hold',campaign_release:'hold',invoice_authority:'draft_only'});toast('BLACKOUT engaged. DIO authority has been narrowed.');await loadState()}catch(e){toast(e.message,true)}}
$("#blackoutBtn").addEventListener('click',blackout);$("#blackoutBtn2").addEventListener('click',blackout);$("#refreshBtn").addEventListener('click',loadState);$("#reconcileBtn").addEventListener('click',()=>runAction('/api/control/transaction/action',{action:'reconcile'},'Reconcile the canonical commercial transaction spine now?'));
$("#registrySearch")?.addEventListener('input',renderRegistry);
setInterval(()=>$("#eyeTime").textContent=new Date().toLocaleTimeString(),1000);loadState();lucide.createIcons();
